services:
  api-gateway:
    build: ./api-gateway
    env_file:
      - ./.env
    environment:
      - PORT=${GATEWAY_PORT}
      - CALENDAR_SERVICE_URL=http://calendar:${CALENDAR_PORT}
      - ACTION_SERVICE_URL=http://action:${ACTION_PORT}
      - HABIT_SERVICE_URL=http://habit:${HABIT_PORT}
      - METRICS_SERVICE_URL=http://metrics:${METRICS_PORT}
      - AUTH_SERVICE_URL=http://auth:${AUTH_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${GATEWAY_PORT}:80"
    depends_on:
      - auth
 #     - calendar
      - action
#      - habit
#      - metrics

  auth:
    build: ./auth-service
    env_file:
      - ./.env
    environment:
      - PORT=${AUTH_PORT}
      - DB_PATH=${AUTH_DB_PATH}
    volumes:
      - ./data/auth/:/data
    ports:
      - "${AUTH_PORT}:8080"

  action:
    build: ./action-service
    env_file:
      - ./.env
    environment:
      - PORT=${ACTION_PORT}
      - DB_PATH=${ACTION_DB_PATH}
    volumes:
      - ./data/action/:/data
    ports:
      - "${ACTION_PORT}:8081"

#  calendar:
#    build: ./calendar-service
#    env_file:
#      - ./.env
#    environment:
#      - PORT=${CALENDAR_PORT}
#      - DB_PATH=${CALENDAR_DB_PATH}
#    volumes:
#      - ./data/calendar/:/data
#    ports:
#      - "${CALENDAR_PORT}:8082"

#  habit:
#    build: ./habit-service
#    env_file:
#      - ./.env
#    environment:
#      - PORT=${HABIT_PORT}
#      - DB_PATH=${HABIT_DB_PATH}
#    volumes:
#      - ./data/habit/:/data
#    ports:
#      - "${HABIT_PORT}:8083"

#  metrics:
#    build: ./metrics-service
#    env_file:
#      - ./.env
#    environment:
#      - PORT=${METRICS_PORT}
#      - DB_PATH=${METRICS_DB_PATH}
#    volumes:
#      - ./data/metrics/:/data
#    ports:
#      - "${METRICS_PORT}:8084"

volumes:
  auth-data:
#  calendar-data:
  action-data:
#  habit-data:
#  metrics-data: